### ISSUE TITLE
Disabling Animals do not prevent them from spawning

### ISSUE THREAD

**Issue by NielsPilgaard** [mc-jt9/ProjectVibrantJourneys#145]
Despite all mobs being disabled in the config, PVJ frogs still spawn.

`projectvibrantjourneys-1.16.5-3.1.0BETA`

My config, trimmed a bit:

```toml

#Project: Vibrant Journeys settings
[Settings]
	[Settings."Mob Settings"]

		[Settings."Mob Settings"."Mob Toggles"]
			"Enable Flies" = false
			"Enable Fireflies" = false
			"Enable Starfish" = false
			"Enable Clams" = false
			"Enable Snails" = false
			"Enable Slugs" = false
			"Enable Small Spiders" = false
			"Enable Frogs" = false

		[Settings."Mob Settings"."Misc Mob Settings"]
			"Mute Flies" = false

		[Settings."Mob Settings"."Vanilla Mob Settings"]
			#Tropical fish in jungles
			jungleTropicalFish = true
			#Bats spawn outside at night
			nightBats = true
```
